
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
#  namespace: argocd
spec:
  destination:
    name: ''
    namespace: cert-manager
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://charts.jetstack.io'
    targetRevision: v1.12.3
    chart: cert-manager
    directory:
      recurse: false
  sources: []
  project: cluster-addons
  syncPolicy:
    automated: null
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true