# https://www.velotio.com/engineering-blog/how-to-deploy-github-actions-self-hosted-runners-on-kubernetes
---
name: First test
on:
 push:
   branches: [ main ]
jobs:
 build:
   name: Install dependencies
   runs-on: self-hosted
   steps:
   - name: Checkout
     uses: actions/checkout@v2
 
   - name: Info runner
     run: |
       echo "### starting workflow ###"
       export TEST=$(hostname)
       echo "This test was executed in $TEST"
       lsb_release -a

   - name: Install dependencies
     run: |
      echo "aws cli"
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install

      echo "clusterctl"
      curl -L https://github.com/kubernetes-sigs/cluster-api/releases/download/v1.5.0/clusterctl-linux-amd64 -o clusterctl
      sudo install -o root -g root -m 0755 clusterctl /usr/local/bin/clusterctl
      clusterctl version

      echo "clusterawsadm"
      curl -L https://github.com/kubernetes-sigs/cluster-api-provider-aws/releases/download/v2.2.1/clusterawsadm-linux-amd64 -o clusterawsadm
      chmod +x clusterawsadm
      install clusterawsadm /usr/local/bin/clusterawsadm

      export AWS_REGION=${{ secrets.AWS_REGION }}
      echo ${{ secrets.AWS_REGION }}
      echo ${{ secrets.AWS_ACCESS_KEY_ID }}
      echo ${{ secrets.AWS_SECRET_ACCESS_KEY }}


