# https://www.velotio.com/engineering-blog/how-to-deploy-github-actions-self-hosted-runners-on-kubernetes
---
name: First test
on:
 push:
   branches: [ main ]
jobs:
 build:
   name: Build-job
   runs-on: self-hosted
   steps:
   - name: Checkout
     uses: actions/checkout@v2
 
   - name: echo
     run: |
       echo "### starting test ###"
       export TEST=$(hostname)
       echo "This test was executed in $TEST"

